/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package adminlogin.car;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Criteria;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.cfg.Configuration;

/**
 *
 * @author micro
 */
public class vehiclebooking extends javax.swing.JFrame {

    /**
     * Creates new form vehiclebooking
     */
    public vehiclebooking() {
        initComponents();
       
    
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bookvehicle = new javax.swing.JPanel();
        datefrom = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        mobileno = new javax.swing.JTextField();
        useremail = new javax.swing.JTextField();
        locationpickup = new javax.swing.JTextField();
        bookamount = new javax.swing.JTextField();
        bookingdate = new javax.swing.JTextField();
        locationdrop = new javax.swing.JTextField();
        vehiclecategory = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        dateto = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bookvehicle.setBackground(new java.awt.Color(102, 204, 255));
        bookvehicle.setOpaque(false);
        bookvehicle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        datefrom.setBorder(null);
        datefrom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datefromActionPerformed(evt);
            }
        });
        bookvehicle.add(datefrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 200, 20));

        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        bookvehicle.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 200, 20));

        mobileno.setBorder(null);
        mobileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobilenoActionPerformed(evt);
            }
        });
        bookvehicle.add(mobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 200, 20));

        useremail.setBorder(null);
        bookvehicle.add(useremail, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 200, 20));

        locationpickup.setBorder(null);
        bookvehicle.add(locationpickup, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 200, 20));

        bookamount.setBorder(null);
        bookvehicle.add(bookamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 200, 20));

        bookingdate.setBorder(null);
        bookvehicle.add(bookingdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, 200, 20));

        locationdrop.setBorder(null);
        bookvehicle.add(locationdrop, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 200, 20));

        vehiclecategory.setBorder(null);
        vehiclecategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehiclecategoryActionPerformed(evt);
            }
        });
        bookvehicle.add(vehiclecategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 210, 20));

        jButton1.setBackground(new java.awt.Color(0, 51, 204));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bookvehicle.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 120, 30));

        dateto.setBorder(null);
        bookvehicle.add(dateto, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, 20));

        jButton2.setBackground(new java.awt.Color(0, 51, 204));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("cancel");
        bookvehicle.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 120, 30));

        getContentPane().add(bookvehicle, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 570, 480));

        jButton8.setBackground(new java.awt.Color(0, 102, 204));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Add Vehicle");
        jButton8.setBorder(null);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 250, 170, 40));

        jButton3.setBackground(new java.awt.Color(0, 102, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("add driver");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 310, 170, 40));

        jButton9.setBackground(new java.awt.Color(0, 102, 204));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("View");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 380, 170, 40));

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminlogin/car/closedicon.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1337, 0, 20, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminlogin/car/toplogo.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 190, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Booking");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 110, 30));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1360, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/adminlogin/car/vehiclebooklo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -40, 1390, 820));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          
        String Vehiclecategory=vehiclecategory.getText();
        Long Dateto=Long.parseLong(dateto.getText());
         Long Datefrom=Long.parseLong(datefrom.getText());
        String Username=username.getText();
        Long Mobileno=Long.parseLong(mobileno.getText());
         String Emailid=useremail.getText();
        String Locationpickup=locationpickup.getText();
        String Locationdrop=locationdrop.getText();
        String Bookingdate=bookingdate.getText();
        String Bookamount=bookamount.getText();      
SessionFactory sessionfac = new Configuration().configure().buildSessionFactory();
Session session=sessionfac.openSession();
Transaction tx=session.beginTransaction();
VehicleBookBean refr= new VehicleBookBean(Vehiclecategory,Dateto,Datefrom,Username,Mobileno,Emailid,Locationpickup,Locationdrop,Bookingdate, Bookamount);  
session.save(refr);
    tx.commit();
      JOptionPane.showMessageDialog(this,"booking successfull...");
      new bookingdata().setVisible(true);
    session.close();
        
       
        
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void mobilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobilenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobilenoActionPerformed

    private void datefromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datefromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datefromActionPerformed

    private void vehiclecategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehiclecategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_vehiclecategoryActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        new addcar().setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new addDriver().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        new bookingdata().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
       
        new vehiclebooking().setVisible(true);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehiclebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehiclebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehiclebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehiclebooking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehiclebooking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookamount;
    private javax.swing.JTextField bookingdate;
    private javax.swing.JPanel bookvehicle;
    private javax.swing.JTextField datefrom;
    private javax.swing.JTextField dateto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField locationdrop;
    private javax.swing.JTextField locationpickup;
    private javax.swing.JTextField mobileno;
    private javax.swing.JTextField useremail;
    private javax.swing.JTextField username;
    private javax.swing.JTextField vehiclecategory;
    // End of variables declaration//GEN-END:variables
}
